### ISSUE TITLE
Constant "Unavailable" cycling.

### ISSUE THREAD

**Issue by jamestalmage** [WillCodeForCats/tekmar-482#59]
I get repeated "attributes changed on device ...", in the logs, but after the reload those attributes report the same.

**Home Assistant (please complete the following information):**
 - Home Assistant Core Version: 2023.11.3
 - Gateway 482 Firmware Version: 154
 - Gateway 482 Protocol Version: 3
 
[home-assistant_tekmar_482_2023-12-01T21-32-31.878Z.log](https://github.com/WillCodeForCats/tekmar-482/files/13532127/home-assistant_tekmar_482_2023-12-01T21-32-31.878Z.log)

**Comment by WillCodeForCats** [comment]
I'll change it to just ignore attributes packets after startup since it should be safe to do so. I'll keep it in mind for the future to do possibly support re-inventory of a single device while running.

The attributes should not actually change unless you're changing setup parameters in the thermostats, and normally that's something you would only do once when it's first installed.

**Comment by WillCodeForCats** [comment]
[Release v0.9.15](https://github.com/WillCodeForCats/tekmar-482/releases/tag/v0.9.15)
